# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------

title: Yuxin Qiu # Your name
email: yuxin.qiu@berkeley.edu
description: > # Write a short description about yourself, or leave blank.
  Undergraduate Researcher at Xi'an Jiaotong University, specializing in Materials Science, 
  Machine Learning, and Data Science. Passionate about the intersection of computational modeling, 
  AI, and experimental materials science.
baseURL: "" # If you are hosting your site at https://USERNAME.github.io/, set this to ""
url: "https://packin-n.github.io" # If you are hosting your site at https://USERNAME.github.io/, set this to "https://USERNAME.github.io"
# repository: "USERNAME/USERNAME.github.io" # If you are hosting your site at https://USERNAME.github.io/, set this to "USERNAME/USERNAME.github.io"

# -----------------------------------------------------------------------------
# Social media
# -----------------------------------------------------------------------------

github_username: "packin-n"
# linkedin_username: "your-linkedin-username" # Add your LinkedIn username here
# scholar_userid: "" # Your Google Scholar ID
# twitter_username: ""

# -----------------------------------------------------------------------------
# General settings
# -----------------------------------------------------------------------------

# GPG (optional)
# gpg:
#   key_id: 384C70B574A96A88
#   key_server: hkps://keyserver.ubuntu.com:443

# -----------------------------------------------------------------------------
# al-folio settings
# -----------------------------------------------------------------------------

# Navigation
nav_items:
  - { title: "About", url: "/" }
  - { title: "Research", url: "/projects/" }
  - { title:Accessory: "Experience", url: "/experience/" }
  - { title: "Education", url: "/education/" }
  - { title: "Personal", url: "/personal/" }

# Footer
#footer_nav_items:
#  - { title: "Sitemap", url: "/sitemap.xml" }

# Theme
theme_settings:
  # The color scheme of the site. Options: light, dark, auto
  color_scheme: "auto"

# -----------------------------------------------------------------------------
# Jekyll settings
# -----------------------------------------------------------------------------

# Used for determining the base and layout directories
root: .

# The directory where the source files are located
source: .

# The directory where the compiled site will be built
destination: ./_site

# The directory to look for plugins
plugins_dir: _plugins

# The directory to look for layouts
layouts_dir: _layouts

# The directory to look for included files
includes_dir: _includes

# The directory to look for data files
data_dir: _data

# A list of files and directories to copy into the destination directory
include:
  - .htaccess
  - _redirects
  - "assets/img" # if you have images, in a file "assets/img"

# A list of files and directories to exclude from the destination directory
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE
  - LICENSE.md
  - README
  - README.md
  - CNAME
  - "assets/js/." # using esbuild/..

# -----------------------------------------------------------------------------
# Jekyll plugins
# -----------------------------------------------------------------------------

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-include-cache
  - jekyll-commonmark-ghpages
  - jekyll-remote-theme # al-folio uses this

# Entry point for building the site
# We use a custom script to build the site, instead of the default `jekyll build`
# command. This script will run `esbuild` to build the JavaScript assets
build_source: "build/build.js"
remote_theme: "alshedivat/al-folio"

# -----------------------------------------------------------------------------
# Markdown settings
# -----------------------------------------------------------------------------

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # default_lang: shell
    css_class: "highlight"

# -----------------------------------------------------------------------------
# Sass settings
# -----------------------------------------------------------------------------

sass:
  style: compressed
  load_paths:
    - _sass
    - node_modules

# -----------------------------------------------------------------------------
# Collections
# -----------------------------------------------------------------------------

collections:
  # The collection of projects
  projects:
    output: true
    # The directory where the project files are located
    # relative to the `collections_dir`
    # (which defaults to the `source` directory)
    # directory: _projects
    # The URL template for projects
    # permalink: /projects/:path/
  
  # The collection of pages
  pages:
    output: true
    # The directory where the page files are located
    # relative to the `collections_dir`
    # (which defaults to the `source` directory)
    directory: _pages
    # The URL template for pages
    permalink: /:path/

# The directory where the collections are located
collections_dir: .

# -----------------------------------------------------------------------------
# Default values
# -----------------------------------------------------------------------------

defaults:
  # Default values for all files
  - scope:
      path: ""
    values:
      layout: default
  # Default values for pages
  - scope:
      type: "pages"
    values:
      layout: page
      # permalink: /:basename/
  # Default values for projects
  - scope:
      type: "projects"
    values:
      layout: project
      # permalink: /projects/:basename/
